/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompareCard: typeof import('./components/graduation_project/process/left_card/CompareCard.vue')['default']
    ControlCard: typeof import('./components/graduation_project/process/left_card/ControlCard.vue')['default']
    ControllCard: typeof import('./components/graduation_project/process/left_card/ControllCard.vue')['default']
    JobSpiderByMajorCard: typeof import('./components/graduation_project/spider/top_card/JobSpiderByMajorCard.vue')['default']
    JobSpiderByPositionCard: typeof import('./components/graduation_project/spider/top_card/JobSpiderByPositionCard.vue')['default']
    MajorJobProcessCard: typeof import('./components/graduation_project/process/right_card/top_right_card/MajorJobProcessCard.vue')['default']
    MajorProcessCard: typeof import('./components/graduation_project/process/right_card/top_right_card/MajorProcessCard.vue')['default']
    MarqueeText: typeof import('./components/public/MarqueeText.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NIcon: typeof import('naive-ui')['NIcon']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NumberCard: typeof import('./components/graduation_project/spider/top_card/NumberCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCard: typeof import('./components/graduation_project/spider/top_card/SearchCard.vue')['default']
    SideMenu: typeof import('./components/graduation_project/menu/SideMenu.vue')['default']
    Temp: typeof import('./components/graduation_project/process/right_card/top_right_card/temp.vue')['default']
    TrainingCountCard: typeof import('./components/graduation_project/spider/bottom_card/TrainingCountCard.vue')['default']
  }
}
