/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./components/graduation_project/achieve/page/dash_board/Bubble.vue')['default']
    BubbleMarker: typeof import('./components/graduation_project/achieve/page/dash_board/BubbleMarker.vue')['default']
    CommunityRecognition: typeof import('./components/graduation_project/achieve/page/major_detail/CommunityRecognition.vue')['default']
    CompareCard: typeof import('./components/graduation_project/achieve/page/dash_board/CompareCard.vue')['default']
    ComparePage: typeof import('./components/graduation_project/achieve/content/ComparePage.vue')['default']
    ControlCard: typeof import('./components/graduation_project/process/left_card/ControlCard.vue')['default']
    ControllCard: typeof import('./components/graduation_project/process/left_card/ControllCard.vue')['default']
    DashBoard: typeof import('./components/graduation_project/achieve/content/DashBoard.vue')['default']
    Diagram: typeof import('./components/graduation_project/achieve/animated/Diagram.vue')['default']
    DomainRadar: typeof import('./components/graduation_project/achieve/page/compare_page/DomainRadar.vue')['default']
    FunctionCard: typeof import('./components/graduation_project/achieve/left_card/FunctionCard.vue')['default']
    HotMajorList: typeof import('./components/graduation_project/achieve/content/HotMajorList.vue')['default']
    HotMajors: typeof import('./components/graduation_project/achieve/page/dash_board/HotMajors.vue')['default']
    JobCascader: typeof import('./components/graduation_project/achieve/left_card/JobCascader.vue')['default']
    JobInfoPanel: typeof import('./components/graduation_project/achieve/page/job_detail/JobInfoPanel.vue')['default']
    JobSpiderByMajorCard: typeof import('./components/graduation_project/spider/top_card/JobSpiderByMajorCard.vue')['default']
    JobSpiderByPositionCard: typeof import('./components/graduation_project/spider/top_card/JobSpiderByPositionCard.vue')['default']
    LayersMap: typeof import('./components/graduation_project/achieve/map/LayersMap.vue')['default']
    MajorCascader: typeof import('./components/graduation_project/achieve/left_card/MajorCascader.vue')['default']
    MajorDetail: typeof import('./components/graduation_project/achieve/content/MajorDetail.vue')['default']
    MajorInfoPanel: typeof import('./components/graduation_project/achieve/page/major_detail/MajorInfoPanel.vue')['default']
    MajorJobProcessCard: typeof import('./components/graduation_project/process/right_card/top_right_card/MajorJobProcessCard.vue')['default']
    MajorProcessCard: typeof import('./components/graduation_project/process/right_card/top_right_card/MajorProcessCard.vue')['default']
    MajorSearch: typeof import('./components/graduation_project/achieve/page/dash_board/MajorSearch.vue')['default']
    Map: typeof import('./components/graduation_project/achieve/map/Map.vue')['default']
    MapContent: typeof import('./components/graduation_project/achieve/map/MapContent.vue')['default']
    MarqueeText: typeof import('./components/public/MarqueeText.vue')['default']
    MatchList: typeof import('./components/graduation_project/achieve/page/job_detail/MatchList.vue')['default']
    MatchScores: typeof import('./components/graduation_project/achieve/page/dash_board/MatchScores.vue')['default']
    ModelCompareCard: typeof import('./components/graduation_project/process/left_card/compare/ModelCompareCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NIcon: typeof import('naive-ui')['NIcon']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NumberCard: typeof import('./components/graduation_project/spider/top_card/NumberCard.vue')['default']
    PositionDetail: typeof import('./components/graduation_project/achieve/content/PositionDetail.vue')['default']
    PositionSearch: typeof import('./components/graduation_project/achieve/page/dash_board/PositionSearch.vue')['default']
    RedBookSpider: typeof import('./components/graduation_project/spider/top_card/RedBookSpider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCard: typeof import('./components/graduation_project/spider/top_card/SearchCard.vue')['default']
    SemanticHeatmap: typeof import('./components/graduation_project/achieve/page/compare_page/SemanticHeatmap.vue')['default']
    SideMenu: typeof import('./components/graduation_project/menu/SideMenu.vue')['default']
    SignBoard: typeof import('./components/graduation_project/achieve/page/dash_board/SignBoard.vue')['default']
    Temp: typeof import('./components/graduation_project/process/right_card/top_right_card/temp.vue')['default']
    Temp_1: typeof import('./components/graduation_project/process/temp_1.vue')['default']
    Temp_3: typeof import('./components/graduation_project/process/temp_3.vue')['default']
    Test: typeof import('./components/graduation_project/achieve/function/test.vue')['default']
    TrainingCountCard: typeof import('./components/graduation_project/spider/bottom_card/TrainingCountCard.vue')['default']
    WaterDrop: typeof import('./components/graduation_project/achieve/animated/WaterDrop.vue')['default']
    WordCloud: typeof import('./components/graduation_project/achieve/page/job_detail/WordCloud.vue')['default']
  }
}
